global using OpenTK.Graphics.OpenGL4;
global using GL = OpenTK.Graphics.OpenGL4.GL;
global using Scripts;
global using Debug = TofuEngine.Debug;
global using TofuEngine;
global using Vector3 = TofuEngine.Vector3;
global using Vector2 = TofuEngine.Vector2;
global using Vector4 = TofuEngine.Vector4;
global using Color = TofuEngine.Color;
global using Matrix4x4 = System.Numerics.Matrix4x4;
global using MathHelper = OpenTK.Mathematics.MathHelper;
global using System;
global using System.Collections.Generic;
global using System.Xml.Serialization;
global using Random = TofuEngine.Random;
// global using NonSerialized = Newtonsoft.Json.JsonIgnoreAttribute;
global using JsonIgnoreAttribute = Newtonsoft.Json.JsonIgnoreAttribute;
namespace TofuEngine;